# Generated by Django 4.2.2 on 2023-09-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solarit_docs',
            name='documents',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
