# Generated by Django 4.2.2 on 2023-09-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarit', '0002_alter_solarit_docs_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarit_docs',
            name='prompt',
            field=models.CharField(default=False, max_length=5000),
        ),
    ]
