# Generated by Django 4.2.2 on 2023-10-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarit', '0003_solarit_docs_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarit_docs',
            name='title',
        ),
    ]
