# Generated by Django 4.2.2 on 2023-10-08 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarit', '0004_remove_solarit_docs_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarit_docs',
            name='prompt',
        ),
    ]
