# Generated by Django 4.2.2 on 2023-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarit', '0006_remove_solarit_docs_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarit_docs',
            name='title',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
