# Generated by Django 4.2.2 on 2023-10-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solarit', '0007_solarit_docs_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='solarit_docs',
            name='title',
            field=models.CharField(blank=True, default=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='solarit_docs',
            name='txt_documents',
            field=models.FileField(blank=True, default=False, upload_to='uploaded_documents/txt_documents/'),
        ),
    ]
